name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

      - name: Shutdown Ubuntu MySQL
        run: sudo service mysql stop

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: 8.0
          mysql database: 'dbname'
          mysql root password: root

      - name: Setup Redis with password
        uses: zhulik/redis-action@1.1.0
        with:
          redis version: '5'

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go mod tidy
      - name: Test Go
        run: go test -v ./...

      - name: Build Go
        run: go build

      - name: End
        run: ls